version: "3.8"

services:
  db:
    image: postgres:13.4
    container_name: smogickdo.postgres
    restart: on-failure
    env_file:
      - envs/dev.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db_migrate:
    image: api:latest
    container_name: smogickdo.migrate
    command: "alembic upgrade head"
    env_file:
      - envs/dev.env
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smogickdo.api
    restart: on-failure
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    env_file:
      - envs/dev.env
    depends_on:
      - db
      - db_migrate

volumes:
  postgres-data: